package h1_one_to_one;
// Generated 29 Nov, 2022 11:28:33 AM by Hibernate Tools 4.3.1



/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private int addressId;
     private Student student;
     private String addressStreet;
     private String addressCity;
     private String addressState;
     private String addressZipcode;

    public Address() {
    }

	
    public Address(Student student) {
        this.student = student;
    }
    public Address(Student student, String addressStreet, String addressCity, String addressState, String addressZipcode) {
       this.student = student;
       this.addressStreet = addressStreet;
       this.addressCity = addressCity;
       this.addressState = addressState;
       this.addressZipcode = addressZipcode;
    }
   
    public int getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(int addressId) {
        this.addressId = addressId;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getAddressStreet() {
        return this.addressStreet;
    }
    
    public void setAddressStreet(String addressStreet) {
        this.addressStreet = addressStreet;
    }
    public String getAddressCity() {
        return this.addressCity;
    }
    
    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }
    public String getAddressState() {
        return this.addressState;
    }
    
    public void setAddressState(String addressState) {
        this.addressState = addressState;
    }
    public String getAddressZipcode() {
        return this.addressZipcode;
    }
    
    public void setAddressZipcode(String addressZipcode) {
        this.addressZipcode = addressZipcode;
    }




}


